#!/usr/bin/env bun
/**
 * Build script: packages terminal-agent as a single Windows exe.
 *
 * Steps:
 *  1. Build the frontend (Vite)
 *  2. Embed all frontend/dist files into backend/src/frontend-assets.ts
 *  3. Compile backend + embedded assets into a self-contained Windows exe
 *     using `bun build --compile --target=bun-windows-x64`
 */

import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import pathModule from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const __dirname = pathModule.dirname(fileURLToPath(import.meta.url));
const rootDir = pathModule.join(__dirname, '..');
const frontendDir = pathModule.join(rootDir, 'frontend');
const backendDir = pathModule.join(rootDir, 'backend');
const frontendDistDir = pathModule.join(frontendDir, 'dist');
const embeddedAssetsFile = pathModule.join(backendDir, 'src', 'frontend-assets.ts');
const outputDir = pathModule.join(rootDir, 'dist');

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript',
  '.mjs': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.txt': 'text/plain',
};

function getMimeType(filePath: string): string {
  const ext = pathModule.extname(filePath).toLowerCase();
  return MIME_TYPES[ext] || 'application/octet-stream';
}

function collectFiles(dir: string, base: string, results: Array<{ urlPath: string; absPath: string }> = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const absPath = pathModule.join(dir, entry.name);
    const urlPath = base + '/' + entry.name;
    if (entry.isDirectory()) {
      collectFiles(absPath, urlPath, results);
    } else {
      results.push({ urlPath, absPath });
    }
  }
  return results;
}

// ── Step 1: Build frontend ────────────────────────────────────────────────────
console.log('📦 Building frontend...');
execSync('npm run build', { cwd: frontendDir, stdio: 'inherit' });
if (!existsSync(frontendDistDir)) {
  console.error('Frontend build failed: dist directory not found');
  process.exit(1);
}
console.log('✅ Frontend built');

// ── Step 2: Generate embedded asset map ──────────────────────────────────────
console.log('🗜️  Embedding frontend assets...');
const files = collectFiles(frontendDistDir, '');
const entries: string[] = [];

for (const { urlPath, absPath } of files) {
  const content = readFileSync(absPath);
  const mimeType = getMimeType(absPath);
  const base64 = content.toString('base64');
  entries.push(
    `  [${JSON.stringify(urlPath)}, { content: Buffer.from(${JSON.stringify(base64)}, 'base64'), mimeType: ${JSON.stringify(mimeType)} }]`
  );
}

const assetMapCode = `// AUTO-GENERATED by scripts/build-exe.ts — do not edit manually
export const frontendAssets: Map<string, { content: Buffer; mimeType: string }> = new Map([\n${entries.join(',\n')}\n]);\n`;

writeFileSync(embeddedAssetsFile, assetMapCode, 'utf-8');
console.log(`✅ Embedded ${files.length} frontend files`);

// ── Step 3: Compile Windows exe ───────────────────────────────────────────────
if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true });
const exePath = pathModule.join(outputDir, 'terminal-agent.exe');

console.log('🔨 Compiling Windows exe (target: bun-windows-x64)...');
console.log(`   Output: ${exePath}`);

execSync(
  `bun build --compile --target=bun-windows-x64 --outfile ${JSON.stringify(exePath)} ${JSON.stringify(pathModule.join(backendDir, 'src', 'index.ts'))}`,
  { cwd: rootDir, stdio: 'inherit', shell: false }
);

// ── Step 4: Restore frontend-assets.ts stub ───────────────────────────────────
// Restore the stub so the source file is not left in a modified state after building.
const STUB_CONTENT = `// Stub file — overwritten by scripts/build-exe.ts when packaging the Windows exe.\n// In dev mode this exports null, causing the backend to serve files from the filesystem.\nexport const frontendAssets: Map<string, { content: Buffer; mimeType: string }> | null = null;\n`;
writeFileSync(embeddedAssetsFile, STUB_CONTENT, 'utf-8');
console.log('✅ Restored frontend-assets.ts stub');

console.log('');
console.log('🎉 Build complete!');
console.log(`   Executable: ${exePath}`);
console.log('');
console.log('📋 Distribution notes:');
console.log('   • Run terminal-agent.exe — no additional files required');
console.log('   • On first run, model-provider.json is auto-created from the built-in template');
console.log('   • The SQLite database is auto-created in the same directory');
